/* Auto-generated by generate_enr_projects.py — DO NOT EDIT */
// Generated: 2026-03-16 11:51
window.ENR_PROJECTS_DATA = {
  "generated": "2026-03-16T11:51:33.027526",
  "week": "09/03/2026",
  "source": "01_Energy/Projet/EnR/",
  "projects": [
    {
      "id": "nosy-be-1",
      "name": "Nosy-Be Phase 1",
      "pvMw": 3.0,
      "bessMwh": null,
      "capexM": 2.783854,
      "tri": 4.2,
      "engStart": "2024-01-09",
      "engEnd": "2025-09-30",
      "engPct": 100,
      "tendDone": true,
      "tendStart": null,
      "tendEnd": null,
      "constStart": "2024-10-10",
      "constEnd": "2026-02-07",
      "costDev": 83854.0,
      "costPv": 2700000.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 1163854
        },
        {
          "q": "Q4-25",
          "a": 810000
        },
        {
          "q": "Q1-26",
          "a": 810000
        }
      ],
      "comment": null,
      "cc": {
        "bac": 3005209,
        "forecast": 2514494,
        "ac": 2067946,
        "avReel": 100,
        "spi": 1.0,
        "cpi": 1.45,
        "perf": "Dans les temps et budget OK"
      },
      "loc": "Nosy-Be",
      "lead": "Lindon",
      "epciste": "SQVISION",
      "puissance": 3000,
      "prodJour": 13890,
      "glissement": 168,
      "constProg": 1.0,
      "engProgression": 100,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 100
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 100
        }
      ],
      "chef": "Lindon",
      "type": "Solaire",
      "phase": "Termine",
      "avancement": 100,
      "blocages": "Levee de reserves en attente",
      "actionsS1": "MES effectuee le 07/02/2026",
      "actionsS": "Paiement EPC solde"
    },
    {
      "id": "tulear-2",
      "name": "Tuléar Phase 2",
      "pvMw": 3.9,
      "bessMwh": null,
      "capexM": 1.355701,
      "engStart": "2024-01-09",
      "engEnd": "2025-08-15",
      "engPct": 100,
      "tendStart": null,
      "tendDone": false,
      "tendEnd": null,
      "constStart": "2024-10-21",
      "constEnd": "2025-07-23",
      "costDev": 18250.0,
      "costPv": 1337451.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 1088211
        },
        {
          "q": "Q4-25",
          "a": 267490
        }
      ],
      "comment": null,
      "cc": {
        "bac": 1458564,
        "forecast": 1219368,
        "ac": 1193232,
        "avReel": 95,
        "spi": 0.95,
        "cpi": 1.16,
        "perf": "En retard mais sous budget"
      },
      "loc": "Tuléar",
      "lead": "Toki",
      "epciste": "MADAGREEN",
      "puissance": 1000,
      "prodJour": 5389,
      "glissement": 61,
      "constProg": 0.98,
      "engProgression": 100,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 100
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 100
        }
      ],
      "chef": "Toki",
      "type": "Solaire",
      "phase": "Termine",
      "avancement": 98,
      "blocages": "Reserves non levees - retour Socotec",
      "actionsS1": "Retour Socotec recu",
      "actionsS": "Action Madagreen planning levee reserves"
    },
    {
      "id": "moramanga-1",
      "name": "Moramanga Phase 1",
      "pvMw": 15.0,
      "bessMwh": null,
      "capexM": 11.123707,
      "tri": 11.4,
      "engStart": "2023-11-21",
      "engEnd": "2025-07-25",
      "engPct": 100,
      "tendDone": true,
      "tendStart": null,
      "tendEnd": null,
      "constStart": "2025-06-06",
      "constEnd": "2026-05-15",
      "costDev": 281720.0,
      "costPv": 10841987.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 281720
        },
        {
          "q": "Q1-26",
          "a": 7589391
        },
        {
          "q": "Q2-26",
          "a": 3252596
        }
      ],
      "comment": null,
      "cc": {
        "bac": 10036607,
        "forecast": 7802433,
        "ac": 3001045,
        "perf": "#VALUE!"
      },
      "loc": "Moramanga",
      "lead": "Lindon",
      "epciste": "BLUESKY",
      "puissance": 15400,
      "prodJour": 80882,
      "glissement": 135,
      "constProg": 0.67,
      "engProgression": 100,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 100
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 100
        }
      ],
      "chef": "Lindon",
      "type": "Solaire",
      "phase": "Construction",
      "avancement": 67,
      "blocages": "Retard dedouanement + logistique route",
      "actionsS1": "Pose module solaire 6.7MW",
      "actionsS": "Poursuite installation structures + modules",
      "paiements": {
        "count": 1,
        "ok": 0,
        "nok": 1,
        "totalMGA": 293405798,
        "lines": [
          {
            "contractant": "MIDEX",
            "prestation": "Dedouanement",
            "desc": "Batch modules",
            "montant": 293405798.0,
            "devise": "MGA",
            "echeance": "2026-04-03",
            "statut": "NOK"
          }
        ]
      }
    },
    {
      "id": "diego-wind-1",
      "name": "Top Energie Diego Wind Phase 1",
      "pvMw": 0.12,
      "bessMwh": null,
      "capexM": 1.074167,
      "tri": 12.9,
      "engStart": "2024-11-15",
      "engEnd": "2026-03-30",
      "engPct": 90,
      "tendDone": true,
      "tendStart": null,
      "tendEnd": null,
      "constStart": "2025-02-23",
      "constEnd": "2026-06-25",
      "costDev": 90000.0,
      "costPv": 984167.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 680500
        },
        {
          "q": "Q4-25",
          "a": 196833
        },
        {
          "q": "Q1-26",
          "a": 196833
        }
      ],
      "comment": null,
      "cc": {
        "bac": 938041,
        "forecast": 1074167,
        "ac": 446723,
        "avReel": 57,
        "spi": 0.57,
        "cpi": 1.2,
        "perf": "En retard mais sous budget"
      },
      "loc": "Diego",
      "lead": "Toki",
      "epciste": "AEOLOS/OTI",
      "puissance": 120,
      "prodJour": 666,
      "glissement": 208,
      "constProg": 0.61,
      "engProgression": 90,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 90
        },
        {
          "name": "Permis Construire",
          "pct": 60
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 100
        }
      ],
      "chef": "Toki",
      "type": "Eolien",
      "phase": "Construction",
      "avancement": 61,
      "blocages": "Permis MEH bloque + retard paiement dedouanement",
      "actionsS1": "OTI 3e/4e paiement OV signe",
      "actionsS": "Dedouanement 10140$ + magasinage 14840$; Relance appel offres 3e shipment",
      "paiements": {
        "count": 6,
        "ok": 2,
        "nok": 4,
        "totalUSD": 223551.0,
        "lines": [
          {
            "contractant": "AEOLOS",
            "prestation": "2nd livraison maritime",
            "desc": "2e shipment",
            "montant": 15600.0,
            "devise": "USD",
            "echeance": "2026-01-15",
            "statut": "OK"
          },
          {
            "contractant": "AEOLOS",
            "prestation": "EPC Materiels",
            "desc": "50% Manufacturing",
            "montant": 68317.0,
            "devise": "USD",
            "statut": "OK"
          },
          {
            "contractant": "AEOLOS",
            "prestation": "EPC Materiels",
            "desc": "Meter purchase",
            "montant": 5000.0,
            "devise": "USD",
            "echeance": "2025-09-22",
            "statut": "NOK",
            "actions": "OV signe, attente nivellement"
          },
          {
            "contractant": "AEOLOS",
            "prestation": "EPC Materiels",
            "desc": "Before shipping rest 5 turbines",
            "montant": 85396.0,
            "devise": "USD",
            "echeance": "2025-12-09",
            "statut": "NOK",
            "actions": "OV signe, attente nivellement"
          },
          {
            "contractant": "OTI",
            "prestation": "Installation eolien",
            "desc": "3e paiement",
            "montant": 24619.0,
            "devise": "USD",
            "echeance": "2025-11-15",
            "statut": "NOK",
            "actions": "OV en cours de preparation"
          },
          {
            "contractant": "OTI",
            "prestation": "Installation eolien",
            "desc": "4e paiement",
            "montant": 24619.0,
            "devise": "USD",
            "echeance": "2025-12-15",
            "statut": "NOK",
            "actions": "Facture receptionnee"
          }
        ]
      }
    },
    {
      "id": "bongatsara-1",
      "name": "Top Energie Ground Solar Bongatsara Phase 1",
      "pvMw": 5.0,
      "bessMwh": 1.5,
      "capexM": 4.735,
      "tri": 11.0,
      "engStart": "2025-04-15",
      "engEnd": "2026-03-15",
      "engPct": 80,
      "tendStart": "2025-12-22",
      "tendDone": false,
      "tendEnd": "2026-03-22",
      "constStart": "2025-12-22",
      "constEnd": "2026-12-30",
      "costDev": 80000.0,
      "costPv": 4655000.0,
      "qtr": [
        {
          "q": "Q4-25",
          "a": 80000
        },
        {
          "q": "Q1-26",
          "a": 1862000
        },
        {
          "q": "Q2-26",
          "a": 1862000
        },
        {
          "q": "Q3-26",
          "a": 931000
        }
      ],
      "comment": null,
      "cc": {
        "bac": 5316367,
        "forecast": 4735000,
        "ac": 25733,
        "avReel": 26,
        "spi": 0.58,
        "cpi": 53.72,
        "perf": "En retard mais sous budget"
      },
      "loc": "Bongatsara",
      "lead": "Lindon",
      "epciste": "CERMAD/TBC",
      "puissance": 5000,
      "prodJour": 24836,
      "glissement": 0,
      "engProgression": 90,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 0
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 50
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 100
        }
      ],
      "chef": "Henintsoa",
      "type": "Solaire",
      "phase": "Construction",
      "avancement": 26,
      "constProg": 0.26,
      "blocages": "ARRET TRAVAUX CERMAD - retard paiement",
      "actionsS1": "Analyse technique EPC Grid Tech vs Bluesky",
      "actionsS": "Reprise paiement CERMAD; Validation SOCOTEC; Choix EPC installateur",
      "paiements": {
        "count": 1,
        "ok": 0,
        "nok": 1,
        "totalMGA": 304913805,
        "lines": [
          {
            "contractant": "CERMAD",
            "prestation": "GC",
            "desc": "25% avancement 50% travaux",
            "montant": 304913805.0,
            "devise": "MGA",
            "echeance": "2026-03-18",
            "statut": "NOK",
            "actions": "ARRET TRAVAUX retard paiement"
          }
        ]
      }
    },
    {
      "id": "diego-lidera",
      "name": "Lidera Diego",
      "pvMw": 10.0,
      "bessMwh": 5.0,
      "capexM": 7.809,
      "tri": 4.2,
      "engStart": "2024-01-03",
      "engEnd": "2026-03-15",
      "engPct": 75,
      "tendStart": "2026-03-25",
      "tendDone": false,
      "tendEnd": "2026-05-10",
      "constStart": "2026-06-15",
      "constEnd": "2027-01-16",
      "costDev": 179000.0,
      "costPv": 7630000.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 89500
        },
        {
          "q": "Q1-26",
          "a": 89500
        },
        {
          "q": "Q2-26",
          "a": 3815000
        },
        {
          "q": "Q3-26",
          "a": 2289000
        },
        {
          "q": "Q4-26",
          "a": 1526000
        }
      ],
      "comment": null,
      "cc": {
        "bac": 24500,
        "forecast": 24500,
        "ac": 0,
        "perf": "#VALUE!"
      },
      "loc": "Diego",
      "lead": "Aymar",
      "epciste": "TBC",
      "puissance": 7600,
      "prodJour": 35730,
      "glissement": 0,
      "engProgression": 75,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 90
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 75
        }
      ],
      "chef": "Aymar",
      "type": "Solaire",
      "phase": "Developpement",
      "avancement": 0,
      "constProg": 0.0,
      "blocages": "Redimensionnement puissances besoins reels",
      "actionsS1": "Etude Geotech LAGEOTECH 100%",
      "actionsS": "Etude offres leasing Ithemba + Scatec; PPA execution",
      "paiements": {
        "count": 1,
        "ok": 0,
        "nok": 1,
        "totalUSD": 953.0,
        "lines": [
          {
            "contractant": "LAGEOTECH",
            "prestation": "Etude geotech",
            "desc": "Acompte demarrage",
            "montant": 953.0,
            "devise": "USD",
            "echeance": "2025-12-02",
            "statut": "NOK",
            "actions": "OV en cours de signature"
          }
        ]
      }
    },
    {
      "id": "mahajanga",
      "name": "Lidera Mahajanga",
      "pvMw": 12.0,
      "bessMwh": 5.0,
      "capexM": 10.635691,
      "tri": 8.6,
      "engStart": "2024-01-03",
      "engEnd": "2026-03-15",
      "engPct": 90,
      "tendStart": "2026-04-01",
      "tendDone": false,
      "tendEnd": "2026-05-10",
      "constStart": "2026-06-15",
      "constEnd": "2027-03-21",
      "costDev": 211000.0,
      "costPv": 10424691.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 105500
        },
        {
          "q": "Q1-26",
          "a": 105500
        },
        {
          "q": "Q2-26",
          "a": 5212346
        },
        {
          "q": "Q3-26",
          "a": 3127407
        },
        {
          "q": "Q1-27",
          "a": 2084938
        }
      ],
      "comment": null,
      "cc": {
        "bac": 20600,
        "forecast": 20600,
        "ac": 0,
        "perf": "#VALUE!"
      },
      "loc": "Majunga",
      "lead": "Aymar",
      "epciste": "TBC",
      "puissance": 10750,
      "prodJour": 51247,
      "glissement": 0,
      "engProgression": 90,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 90
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 75
        }
      ],
      "chef": "Aymar",
      "type": "Solaire",
      "phase": "Developpement",
      "avancement": 0,
      "constProg": 0.0,
      "blocages": "Redimensionnement puissances besoins reels",
      "actionsS1": "Etude Geotech BRG 100%",
      "actionsS": "Paiement solde 50% BRG; Etude offres leasing Ithemba",
      "paiements": {
        "count": 1,
        "ok": 0,
        "nok": 1,
        "totalUSD": 2105.0,
        "lines": [
          {
            "contractant": "BRG",
            "prestation": "Etude geotech",
            "desc": "Acompte 50%",
            "montant": 2105.0,
            "devise": "USD",
            "echeance": "2025-11-02",
            "statut": "NOK",
            "actions": "Facture receptionnee"
          }
        ]
      }
    },
    {
      "id": "tamatave",
      "name": "Lidera Tamatave",
      "pvMw": 20.0,
      "bessMwh": 9.0,
      "capexM": 17.195645,
      "tri": 9.0,
      "engStart": "2024-01-03",
      "engEnd": "2026-06-30",
      "engPct": 50,
      "tendStart": "2026-05-30",
      "tendDone": false,
      "tendEnd": "2026-07-15",
      "constStart": "2026-07-30",
      "constEnd": "2027-03-24",
      "costDev": 234000.0,
      "costPv": 16961645.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 117000
        },
        {
          "q": "Q1-26",
          "a": 117000
        },
        {
          "q": "Q2-26",
          "a": 6784658
        },
        {
          "q": "Q3-26",
          "a": 3392329
        },
        {
          "q": "Q4-26",
          "a": 3392329
        },
        {
          "q": "Q1-27",
          "a": 3392329
        }
      ],
      "comment": "Ph2 - Terrain dispo que pour 16MW + Litige terrain/ Squatters",
      "cc": {
        "bac": 125700,
        "forecast": 125700,
        "ac": 0,
        "perf": "#VALUE!"
      },
      "loc": "Tamatave",
      "lead": "Aymar",
      "epciste": "TBC",
      "puissance": 16000,
      "prodJour": 70619,
      "glissement": 0,
      "constProg": 0.0,
      "engProgression": 50,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 0
        },
        {
          "name": "Etude Geotechnique",
          "pct": 0
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 90
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 50
        },
        {
          "name": "Permis Environnemental",
          "pct": 0
        },
        {
          "name": "Permis Construire",
          "pct": 0
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 0
        }
      ],
      "chef": "Aymar",
      "type": "Solaire",
      "phase": "Developpement",
      "avancement": 0,
      "blocages": "Discussion terrain en cours (Immo)",
      "actionsS1": "Contrat etude geotech signe",
      "actionsS": "Relance Immo terrain; Paiement stand-by attente foncier"
    },
    {
      "id": "nosy-be-2",
      "name": "Nosy-Be Phase 2",
      "pvMw": 2.0,
      "bessMwh": 5.0,
      "capexM": 3.764713,
      "tri": 4.2,
      "engStart": "2024-07-15",
      "engEnd": "2026-03-20",
      "engPct": 90,
      "tendStart": "2026-04-15",
      "tendDone": false,
      "tendEnd": "2026-05-30",
      "constStart": "2026-06-02",
      "constEnd": "2026-11-30",
      "costDev": 34153.0,
      "costPv": 3730560.0,
      "qtr": [
        {
          "q": "Q4-25",
          "a": 34153
        },
        {
          "q": "Q1-26",
          "a": 1119168
        },
        {
          "q": "Q2-26",
          "a": 1119168
        },
        {
          "q": "Q3-26",
          "a": 1119168
        },
        {
          "q": "Q4-26",
          "a": 373056
        }
      ],
      "comment": null,
      "loc": "Nosy-Be",
      "lead": "Lindon",
      "epciste": "TBC",
      "puissance": 2000,
      "prodJour": 9260,
      "glissement": 0,
      "engProgression": 90,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 75
        }
      ],
      "chef": "Lindon",
      "type": "Solaire + BESS",
      "phase": "Developpement",
      "avancement": 0,
      "constProg": 0.0,
      "blocages": "Paiement permis en attente signature contrat EPC",
      "actionsS": "Offres EPC PV+BESS recues; Debut travaux 01/05/26"
    },
    {
      "id": "oursun-1",
      "name": "Oursun ZFI Phase 1",
      "pvMw": 3.2,
      "bessMwh": 1.0,
      "capexM": 5.961194,
      "tri": 11.8,
      "engStart": "2021-01-10",
      "engEnd": "2026-03-20",
      "engPct": 85,
      "tendStart": "2026-04-01",
      "tendDone": false,
      "tendEnd": "2026-05-15",
      "constStart": "2026-05-30",
      "constEnd": "2027-01-30",
      "costDev": 79000.0,
      "costPv": 5882194.0,
      "qtr": [
        {
          "q": "Q4-25",
          "a": 79000
        },
        {
          "q": "Q1-26",
          "a": 2352878
        },
        {
          "q": "Q2-26",
          "a": 1176439
        },
        {
          "q": "Q3-26",
          "a": 1176439
        },
        {
          "q": "Q4-26",
          "a": 1176439
        }
      ],
      "comment": null,
      "cc": {
        "bac": 5782787,
        "forecast": 5961194,
        "ac": 0,
        "avReel": 10,
        "spi": 0.48,
        "perf": "En retard mais sous budget"
      },
      "loc": "Antananarivo",
      "lead": "Henintsoa",
      "epciste": "BLUESKY",
      "puissance": 3200,
      "prodJour": 12099,
      "glissement": 0,
      "engProgression": 85,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 0
        },
        {
          "name": "Etude Geotechnique",
          "pct": 0
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 90
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 70
        }
      ],
      "chef": "Jordy",
      "type": "Solaire",
      "phase": "Developpement",
      "avancement": 10,
      "constProg": 0.1,
      "blocages": "Loyer IMMO impaye 51164 USD (Jan-Dec 2025)",
      "actionsS1": "Etude faisabilite Artelia 70%",
      "actionsS": "Debut travaux 09/06/2026; HSE preparation; Structuration partenariat BlueSky",
      "paiements": {
        "count": 1,
        "ok": 0,
        "nok": 1,
        "totalMGA": 16542762,
        "lines": [
          {
            "contractant": "ARTELIA",
            "prestation": "Etude faisabilite",
            "desc": "40% remise livrable",
            "montant": 16542762.0,
            "devise": "MGA",
            "echeance": "2026-03-06",
            "statut": "NOK"
          }
        ]
      }
    },
    {
      "id": "tulear-3",
      "name": "Tuléar Phase 3",
      "pvMw": 3.1,
      "bessMwh": 2.5,
      "capexM": 3.61125,
      "tri": 11.0,
      "engStart": "2024-01-09",
      "engEnd": "2025-11-30",
      "engPct": 100,
      "tendStart": "2025-12-05",
      "tendDone": false,
      "tendEnd": null,
      "constStart": "2026-04-28",
      "constEnd": "2027-01-23",
      "costDev": 103000.0,
      "costPv": 3508250.0,
      "qtr": [
        {
          "q": "Q4-25",
          "a": 61800
        },
        {
          "q": "Q1-26",
          "a": 41200
        },
        {
          "q": "Q2-26",
          "a": 1754125
        },
        {
          "q": "Q4-26",
          "a": 1754125
        }
      ],
      "comment": null,
      "loc": "Tulear",
      "lead": "Toki",
      "epciste": "TBC",
      "glissement": 0,
      "engProgression": 100,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 100
        }
      ],
      "chef": "Toki",
      "type": "Solaire + BESS",
      "phase": "Developpement",
      "avancement": 0,
      "constProg": 0.0,
      "actionsS1": "Comparatif offres EPC en cours",
      "actionsS": "Appel offres EPC (7 soumissionnaires); Validation SOCOTEC"
    },
    {
      "id": "fihaonana-1",
      "name": "Vestop Fihaonana Phase 1",
      "pvMw": 4.0,
      "bessMwh": null,
      "capexM": 3.63395,
      "tri": 11.9,
      "engStart": "2025-03-18",
      "engEnd": "2026-03-30",
      "engPct": 50,
      "tendStart": "2026-04-05",
      "tendDone": false,
      "tendEnd": "2026-04-30",
      "constStart": "2026-05-04",
      "constEnd": "2026-12-15",
      "costDev": 200000.0,
      "costPv": 3433950.0,
      "qtr": [
        {
          "q": "Q3-25",
          "a": 200000
        },
        {
          "q": "Q2-26",
          "a": 1716975
        },
        {
          "q": "Q3-26",
          "a": 1030185
        },
        {
          "q": "Q4-26",
          "a": 686790
        }
      ],
      "comment": null,
      "cc": {
        "bac": 4333731,
        "forecast": 3633950,
        "ac": 3484,
        "avReel": 24,
        "spi": 0.59,
        "perf": "En retard mais sous budget"
      },
      "loc": "Fihaonana",
      "lead": "Toki",
      "epciste": "TBC",
      "puissance": 4000,
      "prodJour": 20570,
      "glissement": 0,
      "constProg": 0.24,
      "engProgression": 60,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 100
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 80
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 90
        },
        {
          "name": "Permis Environnemental",
          "pct": 0
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 90
        }
      ],
      "chef": "Toki",
      "type": "Solaire",
      "phase": "Developpement",
      "avancement": 24,
      "blocages": "Attente offre ligne evacuation JIRAMA",
      "actionsS1": "Consultation EPC lancee DL 27/03",
      "actionsS": "Depot permis env.; Paiement Geo-Eco 70% restant; Validation controle SOCOTEC",
      "paiements": {
        "count": 2,
        "ok": 0,
        "nok": 2,
        "totalMGA": 40840144,
        "lines": [
          {
            "contractant": "ARTELIA",
            "prestation": "Etude faisabilite",
            "desc": "30% avance signature",
            "montant": 32821000.0,
            "devise": "MGA",
            "echeance": "2026-01-04",
            "statut": "NOK",
            "actions": "Paiement a preparer"
          },
          {
            "contractant": "GEO ECO",
            "prestation": "Etude geotech",
            "desc": "Solde 70%",
            "montant": 8019144.0,
            "devise": "MGA",
            "echeance": "2026-01-17",
            "statut": "NOK",
            "actions": "Paiement a preparer"
          }
        ]
      }
    },
    {
      "id": "moramanga-2",
      "name": "Moramanga Phase 2",
      "pvMw": 25.0,
      "bessMwh": null,
      "capexM": 22.89055,
      "tri": 11.0,
      "engStart": "2025-11-02",
      "engEnd": "2026-06-15",
      "engPct": 35,
      "tendStart": "2026-04-15",
      "tendDone": false,
      "tendEnd": "2026-06-15",
      "constStart": "2026-06-30",
      "constEnd": "2027-05-30",
      "costDev": 300000.0,
      "costPv": 22590550.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 150000
        },
        {
          "q": "Q2-26",
          "a": 11445275
        },
        {
          "q": "Q3-26",
          "a": 6777165
        },
        {
          "q": "Q1-27",
          "a": 4518110
        }
      ],
      "comment": null,
      "loc": "Moramanga",
      "lead": "Lindon",
      "epciste": "TBC",
      "glissement": 0,
      "engProgression": 35,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 80
        },
        {
          "name": "Etude Geotechnique",
          "pct": 0
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 100
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 0
        },
        {
          "name": "Etude Environnementale",
          "pct": 0
        },
        {
          "name": "Permis Environnemental",
          "pct": 0
        },
        {
          "name": "Permis Construire",
          "pct": 0
        },
        {
          "name": "Autorisation ACM",
          "pct": 0
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 0
        }
      ],
      "chef": "Lindon",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "constProg": 0.0,
      "actionsS": "Debut travaux 30/06/2026; CDC a mettre a jour pour consultation EPC"
    },
    {
      "id": "oursun-2",
      "name": "Oursun ZFI Phase 2",
      "pvMw": 7.8,
      "bessMwh": 2.0,
      "capexM": 7.86458,
      "tri": 12.0,
      "engStart": "2021-01-10",
      "engEnd": "2026-09-30",
      "engPct": 85,
      "tendStart": "2026-10-01",
      "tendDone": false,
      "tendEnd": "2026-12-15",
      "constStart": "2027-01-25",
      "constEnd": "2027-11-20",
      "costDev": 60000.0,
      "costPv": 7804580.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 42000
        },
        {
          "q": "Q2-26",
          "a": 18000
        },
        {
          "q": "Q3-26",
          "a": 2341374
        },
        {
          "q": "Q1-27",
          "a": 2341374
        },
        {
          "q": "Q3-27",
          "a": 2341374
        },
        {
          "q": "Q4-27",
          "a": 780458
        }
      ],
      "comment": null,
      "loc": "Antananarivo",
      "lead": "Henintsoa",
      "epciste": "TBC",
      "puissance": 7800,
      "prodJour": 29490,
      "glissement": 0,
      "constProg": 0.0,
      "engProgression": 85,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 0
        },
        {
          "name": "Etude Geotechnique",
          "pct": 0
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 90
        },
        {
          "name": "Etude de Ligne",
          "pct": 100
        },
        {
          "name": "Categorisation Env.",
          "pct": 100
        },
        {
          "name": "Etude Environnementale",
          "pct": 100
        },
        {
          "name": "Permis Environnemental",
          "pct": 100
        },
        {
          "name": "Permis Construire",
          "pct": 100
        },
        {
          "name": "Autorisation ACM",
          "pct": 100
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 0
        }
      ],
      "chef": "Jordy",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "blocages": "Renforcement toiture en cours",
      "actionsS": "Attente toiture renforcee"
    },
    {
      "id": "small-sites",
      "name": "Small Sites : Ihosy, Sakaraha, Maintirano, Ranohira",
      "pvMw": 2.18,
      "bessMwh": null,
      "capexM": 2.3,
      "tri": 3.0,
      "engStart": "2026-03-22",
      "engEnd": "2026-08-15",
      "engPct": 0,
      "tendStart": "2026-10-10",
      "tendDone": false,
      "tendEnd": "2026-11-20",
      "constStart": "2026-12-05",
      "constEnd": "2027-07-20",
      "costDev": 300000.0,
      "costPv": 2000000.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 150000
        },
        {
          "q": "Q2-26",
          "a": 150000
        },
        {
          "q": "Q3-26",
          "a": 600000
        },
        {
          "q": "Q1-27",
          "a": 600000
        },
        {
          "q": "Q2-27",
          "a": 600000
        },
        {
          "q": "Q3-27",
          "a": 200000
        }
      ],
      "comment": "Terrains indisponibles - En cours de discussions avec La JIRAMA",
      "loc": "Ihosy, Ranohira, Sakaraha & Maintirano",
      "lead": "Aymar",
      "epciste": "OTC/BLUESKY",
      "glissement": 0,
      "constProg": 0.0,
      "engProgression": 0,
      "chef": "Aymar",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "blocages": "Terrains indisponibles Ihosy/Ranohira",
      "actionsS": "Offres leasing recues 3 sites; Consultation BlueSky envoyee 27/02; Confirmation descente sites"
    },
    {
      "id": "ambohidratrimo",
      "name": "Top Energie Ambohidratrimo (Ambohijanaka)",
      "pvMw": 10.0,
      "bessMwh": 2.5,
      "capexM": 10.41514,
      "tri": 11.0,
      "engStart": "2026-03-10",
      "engEnd": "2026-08-30",
      "engPct": 0,
      "tendStart": "2026-09-05",
      "tendDone": false,
      "tendEnd": "2026-09-30",
      "constStart": "2026-10-01",
      "constEnd": "2027-10-07",
      "costDev": 210000.0,
      "costPv": 10205140.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 126000
        },
        {
          "q": "Q2-26",
          "a": 84000
        },
        {
          "q": "Q4-26",
          "a": 5102570
        },
        {
          "q": "Q2-27",
          "a": 5102570
        }
      ],
      "comment": "En cours d'analyse terrain @Ambohijanaka",
      "loc": "Ambohidratrimo",
      "lead": "Toki",
      "epciste": "TBC",
      "puissance": 10000,
      "prodJour": 50548,
      "glissement": 0,
      "chef": "Toki",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "constProg": 0.0,
      "blocages": "Changement terrain",
      "actionsS": "Validation terrain Ambohimalaza pour 5MW"
    },
    {
      "id": "diego-wind-2",
      "name": "Top Energie Diego Wind Phase 2",
      "pvMw": 4.88,
      "bessMwh": null,
      "capexM": 7.14056,
      "tri": 12.9,
      "engStart": "2026-02-01",
      "engEnd": "2026-09-30",
      "engPct": 0,
      "tendStart": "2026-08-30",
      "tendDone": false,
      "tendEnd": "2026-09-30",
      "constStart": "2026-10-20",
      "constEnd": "2027-09-15",
      "costDev": 250000.0,
      "costPv": 6890560.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 125000
        },
        {
          "q": "Q2-26",
          "a": 125000
        },
        {
          "q": "Q3-26",
          "a": 2756224
        },
        {
          "q": "Q1-27",
          "a": 2756224
        },
        {
          "q": "Q3-27",
          "a": 1378112
        }
      ],
      "comment": null,
      "loc": "Diego",
      "lead": "Toki",
      "epciste": "TBC",
      "glissement": 0,
      "engProgression": 0,
      "chef": "Toki",
      "type": "Eolien",
      "phase": "Planifie",
      "avancement": 0,
      "constProg": 0.0,
      "actionsS": "Consultation etude faisabilite; Etude Topo debut avril"
    },
    {
      "id": "marais-masay",
      "name": "Top Energie Floating Solar Marais Masay",
      "pvMw": 10.0,
      "bessMwh": 2.5,
      "capexM": 12.985253,
      "engStart": "2026-02-02",
      "engEnd": "2026-07-30",
      "engPct": 0,
      "tendStart": "2026-08-10",
      "tendDone": false,
      "tendEnd": "2026-10-25",
      "constStart": "2026-11-04",
      "constEnd": "2027-11-10",
      "costDev": 190000.0,
      "costPv": 12795253.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 57000
        },
        {
          "q": "Q2-26",
          "a": 76000
        },
        {
          "q": "Q3-26",
          "a": 57000
        },
        {
          "q": "Q1-27",
          "a": 6397626
        },
        {
          "q": "Q3-27",
          "a": 3838576
        },
        {
          "q": "Q4-27",
          "a": 2559051
        }
      ],
      "comment": null,
      "loc": "Marais Masay",
      "lead": "Aymar/ Henintsoa",
      "epciste": "TBC",
      "glissement": 0,
      "constProg": 0.0,
      "engProgression": 0,
      "chef": "Aymar",
      "type": "Flottant",
      "phase": "Planifie",
      "avancement": 0,
      "blocages": "Devis BRG en attente validation DG depuis 27/01",
      "actionsS1": "Envoi docs techniques NTPC par Sayouba",
      "actionsS": "Acquisition lac - procedure fonciere; Confirmation JIRAMA ligne evacuation"
    },
    {
      "id": "bongatsara-2",
      "name": "Top Energie Ground Solar Bongatsara Phase 2 (Ambohimalaza)",
      "pvMw": 5.0,
      "bessMwh": 1.5,
      "capexM": 4.775,
      "tri": 6.7,
      "engStart": "2026-02-15",
      "engEnd": "2026-08-15",
      "engPct": 0,
      "tendStart": "2026-08-15",
      "tendDone": false,
      "tendEnd": "2026-10-05",
      "constStart": "2026-10-10",
      "constEnd": "2027-08-12",
      "costDev": 120000.0,
      "costPv": 4655000.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 120000
        },
        {
          "q": "Q2-26",
          "a": 2327500
        },
        {
          "q": "Q4-26",
          "a": 1396500
        },
        {
          "q": "Q2-27",
          "a": 931000
        }
      ],
      "comment": "Terrain en litige + @ 30% de couts supplémentaires GC v/s Phase 1",
      "loc": "Bongatsara",
      "lead": "Lindon",
      "epciste": "TBC",
      "glissement": 0,
      "engProgression": 0,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 0
        },
        {
          "name": "Etude Geotechnique",
          "pct": 0
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 0
        },
        {
          "name": "Etude de Ligne",
          "pct": 0
        },
        {
          "name": "Categorisation Env.",
          "pct": 0
        },
        {
          "name": "Etude Environnementale",
          "pct": 40
        },
        {
          "name": "Permis Environnemental",
          "pct": 0
        },
        {
          "name": "Permis Construire",
          "pct": 0
        },
        {
          "name": "Autorisation ACM",
          "pct": 0
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 0
        }
      ],
      "chef": "Henintsoa",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "constProg": 0.0,
      "blocages": "Changement terrain vers Ambohijanaka",
      "actionsS": "Terrain pas encore defini"
    },
    {
      "id": "fihaonana-2",
      "name": "Vestop Fihaonana Phase 2",
      "pvMw": 15.0,
      "bessMwh": 7.5,
      "capexM": 15.538654,
      "tri": 11.9,
      "engStart": "2026-03-01",
      "engEnd": "2026-06-15",
      "engPct": 0,
      "tendStart": "2026-07-15",
      "tendDone": false,
      "tendEnd": "2026-08-15",
      "constStart": "2026-10-15",
      "constEnd": "2027-06-15",
      "costDev": 230000.0,
      "costPv": 15308654.0,
      "qtr": [
        {
          "q": "Q1-26",
          "a": 138000
        },
        {
          "q": "Q2-26",
          "a": 7746327
        },
        {
          "q": "Q4-26",
          "a": 4592596
        },
        {
          "q": "Q1-27",
          "a": 3061731
        }
      ],
      "comment": null,
      "loc": "Fihaonana",
      "lead": "Toki",
      "epciste": "TBC",
      "glissement": 0,
      "engProgression": 10,
      "studies": [
        {
          "name": "Etude Topographique",
          "pct": 100
        },
        {
          "name": "Etude Geotechnique",
          "pct": 30
        },
        {
          "name": "Test Arrachement",
          "pct": 0
        },
        {
          "name": "Etude Faisabilite",
          "pct": 20
        },
        {
          "name": "Etude de Ligne",
          "pct": 0
        },
        {
          "name": "Categorisation Env.",
          "pct": 0
        },
        {
          "name": "Etude Environnementale",
          "pct": 40
        },
        {
          "name": "Permis Environnemental",
          "pct": 0
        },
        {
          "name": "Permis Construire",
          "pct": 0
        },
        {
          "name": "Autorisation ACM",
          "pct": 0
        },
        {
          "name": "Etude Technico-Financiere",
          "pct": 0
        }
      ],
      "chef": "Toki",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "constProg": 0.0,
      "actionsS": "Attente offres etude faisabilite + geotech; DL validation env. 18/03"
    },
    {
      "id": "lidera-toamasina-3",
      "loc": "Tamatave",
      "lead": "Aymar",
      "epciste": "TBC",
      "puissance": 16000,
      "prodJour": 70619,
      "glissement": 0,
      "chef": "Aymar",
      "type": "Solaire",
      "phase": "Planifie",
      "avancement": 0,
      "constProg": 0.0,
      "name": "lidera-toamasina-3"
    }
  ]
};
