"""Generate reporting_data.js from Weekly EnR Excel files."""
import json, os, sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

import openpyxl

BASE = r"C:\Users\Meril\OneDrive - GROUPE FILATEX\Fichiers de DOSSIER DASHBOARD - Data_Dashbords\01_Energy\Projet\EnR"
AVANCEMENT_FILE = os.path.join(BASE, "Weekly_EnR_Avancement.xlsx")
PAIEMENTS_FILE = os.path.join(BASE, "Weekly_EnR_Paiements.xlsx")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reporting_data.js")


def safe_str(v):
    if v is None:
        return ""
    return str(v).strip()


def safe_num(v, default=0):
    if v is None:
        return default
    try:
        return float(v)
    except (ValueError, TypeError):
        return default


def read_avancement():
    if not os.path.exists(AVANCEMENT_FILE):
        print(f"WARN: {AVANCEMENT_FILE} not found")
        return None, []

    wb = openpyxl.load_workbook(AVANCEMENT_FILE, data_only=True)
    ws = wb["Avancement Projets"]

    # Read week date from E2
    week_val = ws["E2"].value
    week_str = ""
    if week_val:
        if hasattr(week_val, 'strftime'):
            week_str = week_val.strftime("%d/%m/%Y")
        else:
            week_str = str(week_val)

    # Read projects starting at row 5
    projects = []
    for row in range(5, ws.max_row + 1):
        pid = safe_str(ws.cell(row, 1).value)
        nom = safe_str(ws.cell(row, 2).value)
        if not pid and not nom:
            continue

        projects.append({
            "id": pid,
            "projet": nom,
            "responsable": safe_str(ws.cell(row, 3).value),
            "type": safe_str(ws.cell(row, 4).value),
            "puissance": safe_num(ws.cell(row, 5).value),
            "phase": safe_str(ws.cell(row, 6).value),
            "avancement": safe_num(ws.cell(row, 7).value),
            "glissement": int(safe_num(ws.cell(row, 8).value)),
            "statut_eng": safe_str(ws.cell(row, 9).value),
            "statut_const": safe_str(ws.cell(row, 10).value),
            "statut_permis": safe_str(ws.cell(row, 11).value),
            "epc": safe_str(ws.cell(row, 12).value),
            "date_mes_prevue": safe_str(ws.cell(row, 13).value),
            "date_mes_revisee": safe_str(ws.cell(row, 14).value),
            "blocages": safe_str(ws.cell(row, 15).value),
            "actions_s1": safe_str(ws.cell(row, 16).value),
            "actions": safe_str(ws.cell(row, 17).value),
            "commentaires_dg": safe_str(ws.cell(row, 18).value),
        })

    wb.close()
    return week_str, projects


def read_paiements():
    if not os.path.exists(PAIEMENTS_FILE):
        print(f"WARN: {PAIEMENTS_FILE} not found")
        return []

    wb = openpyxl.load_workbook(PAIEMENTS_FILE, data_only=True)
    ws = wb["Paiements"]

    payments = []
    for row in range(5, ws.max_row + 1):
        pid = safe_str(ws.cell(row, 1).value)
        projet = safe_str(ws.cell(row, 2).value)
        if not pid and not projet:
            continue
        # Skip summary rows
        if safe_str(ws.cell(row, 5).value).startswith("TOTAL"):
            continue

        payments.append({
            "id_projet": pid,
            "projet": projet,
            "contractant": safe_str(ws.cell(row, 3).value),
            "prestation": safe_str(ws.cell(row, 4).value),
            "description": safe_str(ws.cell(row, 5).value),
            "montant": safe_num(ws.cell(row, 6).value),
            "devise": safe_str(ws.cell(row, 7).value),
            "echeance": safe_str(ws.cell(row, 8).value),
            "statut": safe_str(ws.cell(row, 9).value),
            "actions": safe_str(ws.cell(row, 10).value),
        })

    wb.close()
    return payments


def main():
    week, projects = read_avancement()
    payments = read_paiements()

    data = {
        "week": week or "",
        "generated": __import__('datetime').datetime.now().isoformat(),
        "projects": projects,
        "payments": payments,
    }

    js = "/* Auto-generated by generate_reporting.py — DO NOT EDIT */\nwindow.REPORTING_ENR = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"OK: {OUT}")
    print(f"  Week: {week}")
    print(f"  Projects: {len(projects)}")
    print(f"  Payments: {len(payments)}")


if __name__ == "__main__":
    main()
